-- shiroki-mori - A light theme based on wildcharm with additional highlight customizations

-- Reset highlighting.
vim.cmd.highlight('clear')
if vim.fn.exists('syntax_on') then
  vim.cmd.syntax('reset')
end

vim.g.colors_name = 'shiroki-mori'
vim.opt.termguicolors = true

local colors = {
  -- Background colors
  bg = '#ececec',
  bg_light = '#e1e1e1',
  bg_lighter = '#eeeeee',
  bg_popup = '#e4e4e4',
  bg_statusline = '#5f5f5f',
  bg_statusline_nc = '#d0d0d0',
  bg_fold = '#e4e4e4',
  bg_diff_add = '#afd7af',
  bg_diff_change = '#dadada',
  bg_diff_delete = '#ffd7d7',
  bg_diff_text = '#afd7d7',
  bg_search = '#008700',
  bg_incsearch = '#d78700',
  bg_visual = '#ffffff',
  bg_pmenu_sel = '#b2b2b2',
  bg_quickfix = '#870087',
  bg_wildmenu = '#d78700',

  -- Foreground colors
  fg = '#000000',
  fg_white = '#ffffff',
  fg_grey = '#8a8a8a',
  fg_grey_light = '#b2b2b2',
  fg_grey_dark = '#808080',
  fg_comment = '#8a8a8a',

  -- Syntax colors
  red = '#af0000',
  red_bright = '#d70000',
  green = '#008700',
  green_bright = '#5faf5f',
  yellow = '#af5f00',
  yellow_bright = '#0087d7',
  blue = '#005faf',
  blue_bright = '#005f87',
  magenta = '#870087',
  magenta_bright = '#5f00d7',
  cyan = '#008787',
  cyan_bright = '#458588',
  orange = '#af5f00',
  purple = '#5f00d7',
  pink = '#ff00af',

  -- UI colors
  line_nr = '#b2b2b2',
  cursor_line_nr = '#000000',
  non_text = '#909090',
  vert_split = '#5f5f5f',
  statusline_fg = '#ffffff',
  statusline_nc_fg = '#000000',

  -- Diagnostic colors
  diag_error = '#ff0000',
  diag_warn = '#af5f00',
  diag_info = '#005f87',
  diag_hint = '#458588',
  diag_ok = '#90ee90',

  -- Git colors
  git_add = '#005f00',
  git_change = '#262626',
  git_delete = '#875f5f',
  git_staged_add = '#afd7af',
  git_staged_change = '#7fc3eb',
  git_staged_delete = '#eb7f7f',
}

-- Terminal colors (light theme)
vim.g.terminal_color_0 = '#000000'
vim.g.terminal_color_1 = colors.red_bright
vim.g.terminal_color_2 = colors.green
vim.g.terminal_color_3 = colors.yellow
vim.g.terminal_color_4 = colors.blue
vim.g.terminal_color_5 = colors.magenta
vim.g.terminal_color_6 = colors.cyan
vim.g.terminal_color_7 = colors.fg_white
vim.g.terminal_color_8 = colors.fg_grey
vim.g.terminal_color_9 = colors.red_bright
vim.g.terminal_color_10 = colors.green_bright
vim.g.terminal_color_11 = colors.orange
vim.g.terminal_color_12 = colors.blue_bright
vim.g.terminal_color_13 = colors.magenta_bright
vim.g.terminal_color_14 = colors.cyan_bright
vim.g.terminal_color_15 = colors.fg_white
vim.g.terminal_color_background = colors.bg
vim.g.terminal_color_foreground = colors.fg

---@type table<string, vim.api.keyset.highlight>
local groups = {
  -- Builtins
  Boolean = { link = 'Constant' },
  Character = { link = 'Constant' },
  ColorColumn = { bg = colors.bg_light },
  Comment = { fg = colors.fg_comment },
  Conceal = { fg = colors.fg_grey_light },
  Conditional = { link = 'Statement' },
  Constant = { fg = colors.red },
  CurSearch = { link = 'IncSearch' },
  Cursor = { fg = colors.fg_white, bg = colors.fg },
  CursorColumn = { bg = colors.bg_lighter },
  CursorIM = { link = 'Cursor' },
  CursorLine = { bg = colors.bg_light },
  CursorLineFold = { link = 'FoldColumn' },
  CursorLineNr = { fg = colors.cursor_line_nr, bold = true },
  CursorLineSign = { link = 'SignColumn' },
  Debug = { link = 'Special' },
  Define = { link = 'PreProc' },
  Delimiter = { link = 'Special' },
  DiagnosticDeprecated = { strikethrough = true, sp = colors.diag_error },
  DiagnosticError = { fg = colors.diag_error },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticHint = { fg = colors.diag_hint },
  DiagnosticInfo = { fg = colors.diag_info },
  DiagnosticOk = { fg = colors.diag_ok },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticUnderlineError = { undercurl = true },
  DiagnosticUnderlineHint = { underline = true, sp = '#d3d3d3' },
  DiagnosticUnderlineInfo = { undercurl = true, sp = colors.diag_info },
  DiagnosticUnderlineOk = { underline = true, sp = '#90ee90' },
  DiagnosticUnderlineWarn = { undercurl = true, sp = colors.diag_warn },
  DiagnosticUnnecessary = { link = 'Comment' },
  DiagnosticVirtualLinesError = { link = 'DiagnosticError' },
  DiagnosticVirtualLinesHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualLinesInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualLinesOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualLinesWarn = { link = 'DiagnosticWarn' },
  DiagnosticVirtualTextError = { link = 'DiagnosticError' },
  DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
  DiagnosticWarn = { fg = colors.diag_warn },
  DiffAdd = { fg = colors.git_add, bg = colors.bg_diff_add },
  DiffChange = { fg = colors.git_change, bg = colors.bg_diff_change },
  DiffDelete = { fg = colors.git_delete, bg = colors.bg_diff_delete },
  DiffText = { fg = '#005f5f', bg = colors.bg_diff_text },
  Directory = { fg = colors.blue, bold = true },
  EndOfBuffer = { fg = colors.fg_grey_light },
  Error = { fg = colors.red_bright, bg = colors.fg_white, reverse = true },
  ErrorMsg = { fg = colors.red_bright, bg = colors.fg_white, reverse = true },
  Exception = { link = 'Statement' },
  Float = { link = 'Number' },
  FloatBorder = { link = 'WinSeparator' },
  FloatFooter = { link = 'Title' },
  FloatShadow = { bg = '#000000', blend = 80 },
  FloatShadowThrough = { bg = '#000000', blend = 100 },
  FloatTitle = { link = 'Title' },
  FoldColumn = { fg = colors.fg_grey_light },
  Folded = { fg = colors.fg_grey_dark, bg = colors.bg_fold },
  Function = { link = 'Identifier' },
  Identifier = { fg = colors.magenta },
  Ignore = {},
  IncSearch = { fg = colors.fg_white, bg = colors.bg_incsearch },
  Include = { link = 'PreProc' },
  Keyword = { link = 'Statement' },
  Label = { link = 'Statement' },
  LineNr = { fg = colors.line_nr },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  LspCodeLens = { link = 'NonText' },
  LspCodeLensSeparator = { link = 'LspCodeLens' },
  LspInlayHint = { link = 'NonText' },
  LspReferenceRead = { link = 'LspReferenceText' },
  LspReferenceTarget = { link = 'LspReferenceText' },
  LspReferenceText = { link = 'Visual' },
  LspReferenceWrite = { link = 'LspReferenceText' },
  LspSignatureActiveParameter = { link = 'Visual' },
  Macro = { link = 'PreProc' },
  MatchBackground = { link = 'ColorColumn' },
  MatchParen = { fg = colors.pink, bold = true },
  MatchParenCur = { link = 'MatchParen' },
  MatchWord = { link = 'MatchParen' },
  ModeMsg = { bold = true },
  MoreMsg = { fg = colors.green },
  MsgArea = {},
  MsgSeparator = { link = 'StatusLine' },
  NonText = { fg = colors.non_text },
  Normal = { bg = colors.bg },
  NormalFloat = { link = 'Pmenu' },
  NormalNC = {},
  Number = { link = 'Constant' },
  Operator = { link = 'Statement' },
  Pmenu = { fg = colors.fg, bg = colors.bg_popup },
  PmenuExtra = { fg = colors.fg_grey_dark, bg = colors.bg_popup },
  PmenuExtraSel = { fg = colors.fg_grey_dark, bg = colors.bg_pmenu_sel },
  PmenuKind = { fg = colors.red_bright, bg = colors.bg_popup },
  PmenuKindSel = { fg = colors.red_bright, bg = colors.bg_pmenu_sel },
  PmenuMatch = { fg = colors.magenta, bg = colors.bg_popup },
  PmenuMatchSel = { fg = colors.magenta, bg = colors.bg_pmenu_sel },
  PmenuSbar = {},
  PmenuSel = { fg = colors.fg, bg = colors.bg_pmenu_sel },
  PmenuThumb = { bg = colors.fg_grey_dark },
  PreCondit = { link = 'PreProc' },
  PreProc = { fg = colors.cyan },
  Question = { fg = colors.magenta },
  QuickFixLine = { fg = colors.fg_white, bg = colors.bg_quickfix },
  RedrawDebugClear = { bg = '#ffff00' },
  RedrawDebugComposed = { bg = '#00ff00' },
  RedrawDebugNormal = { reverse = true },
  RedrawDebugRecompose = { bg = '#ff0000' },
  Repeat = { link = 'Statement' },
  Search = { fg = colors.fg_white, bg = colors.bg_search },
  SignColumn = {},
  Special = { fg = colors.purple },
  SpecialChar = { link = 'Special' },
  SpecialComment = { link = 'Special' },
  SpecialKey = { fg = colors.fg_grey_light },
  SpellBad = { undercurl = true, sp = '#af0000' },
  SpellCap = { undercurl = true, sp = colors.cyan },
  SpellLocal = { undercurl = true, sp = colors.green },
  SpellRare = { undercurl = true, sp = '#af00af' },
  Statement = { fg = colors.blue },
  StatusLine = { fg = colors.statusline_fg, bg = colors.bg_statusline, bold = true },
  StatusLineNC = { fg = colors.statusline_nc_fg, bg = colors.bg_statusline_nc },
  StatusLineTerm = { fg = '#ffffff', bg = '#006400', bold = true },
  StatusLineTermNC = { fg = '#ffffff', bg = '#006400' },
  StorageClass = { link = 'Type' },
  String = { fg = colors.green },
  Structure = { link = 'Type' },
  Substitute = { link = 'Search' },
  TabLine = { fg = colors.fg, bg = colors.bg_statusline_nc },
  TabLineFill = {},
  TabLineSel = { fg = colors.bg_statusline, bg = colors.fg_white, bold = true, reverse = true },
  Tag = { link = 'Special' },
  TermCursor = { reverse = true },
  Title = { bold = true },
  Todo = { fg = colors.purple, bg = colors.fg_white, reverse = true },
  ToolbarButton = { fg = colors.fg_white, bg = colors.bg_statusline },
  ToolbarLine = {},
  Type = { fg = colors.orange },
  Typedef = { link = 'Type' },
  Underlined = { underline = true },
  VertSplit = { fg = colors.vert_split },
  Visual = { fg = colors.blue_bright, bg = colors.bg_visual, reverse = true },
  VisualNC = {},
  VisualNOS = { fg = colors.fg_white, bg = colors.blue },
  WarningMsg = { fg = colors.yellow },
  Whitespace = { link = 'NonText' },
  WildMenu = { fg = colors.fg_white, bg = colors.bg_wildmenu },
  WinBar = { bold = true },
  WinBarNC = { link = 'WinBar' },
  WinSeparator = { link = 'VertSplit' },
  lCursor = { fg = colors.fg, bg = '#ff00ff' },

  -- Treesitter
  ['@attribute'] = { link = 'Macro' },
  ['@attribute.builtin'] = { link = 'Special' },
  ['@boolean'] = { link = 'Boolean' },
  ['@character'] = { link = 'Character' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@comment'] = { link = 'Comment' },
  ['@comment.error'] = { link = 'DiagnosticError' },
  ['@comment.note'] = { link = 'DiagnosticInfo' },
  ['@comment.todo'] = { link = 'Todo' },
  ['@comment.warning'] = { link = 'DiagnosticWarn' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Special' },
  ['@constant.macro'] = { link = 'Define' },
  ['@constructor'] = { link = 'Special' },
  ['@diff'] = {},
  ['@diff.delta'] = { link = 'Changed' },
  ['@diff.minus'] = { link = 'Removed' },
  ['@diff.plus'] = { link = 'Added' },
  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'Special' },
  ['@function.macro'] = { link = 'Macro' },
  ['@function.method'] = { link = 'Function' },
  ['@keyword'] = { link = 'Keyword' },
  ['@keyword.conditional'] = { link = 'Conditional' },
  ['@keyword.debug'] = { link = 'Debug' },
  ['@keyword.directive'] = { link = 'PreProc' },
  ['@keyword.exception'] = { link = 'Exception' },
  ['@keyword.import'] = { link = 'Include' },
  ['@keyword.repeat'] = { link = 'Repeat' },
  ['@keyword.type'] = { link = 'Structure' },
  ['@label'] = { link = 'Label' },
  ['@lsp'] = {},
  ['@lsp.mod.deprecated'] = { link = 'DiagnosticDeprecated' },
  ['@lsp.type.class'] = { link = 'Structure' },
  ['@lsp.type.comment'] = { link = 'Comment' },
  ['@lsp.type.decorator'] = { link = 'Function' },
  ['@lsp.type.enum'] = { link = 'Structure' },
  ['@lsp.type.enumMember'] = { link = 'Constant' },
  ['@lsp.type.event'] = { link = '@type' },
  ['@lsp.type.function'] = { link = 'Function' },
  ['@lsp.type.interface'] = { link = 'Structure' },
  ['@lsp.type.keyword'] = { link = '@keyword' },
  ['@lsp.type.macro'] = { link = 'Macro' },
  ['@lsp.type.method'] = { link = 'Function' },
  ['@lsp.type.modifier'] = { link = '@type.qualifier' },
  ['@lsp.type.namespace'] = { link = 'Structure' },
  ['@lsp.type.number'] = { link = '@number' },
  ['@lsp.type.operator'] = { link = '@operator' },
  ['@lsp.type.parameter'] = { link = 'Identifier' },
  ['@lsp.type.property'] = { link = 'Identifier' },
  ['@lsp.type.regexp'] = { link = '@string.regexp' },
  ['@lsp.type.string'] = { link = '@string' },
  ['@lsp.type.struct'] = { link = 'Structure' },
  ['@lsp.type.type'] = { link = 'Type' },
  ['@lsp.type.typeParameter'] = { link = 'Typedef' },
  ['@lsp.type.variable'] = { link = 'Identifier' },
  ['@markup'] = { link = 'Special' },
  ['@markup.heading'] = { link = 'Title' },
  ['@markup.heading.1.delimiter.vimdoc'] = {
    underdouble = true,
    nocombine = true,
    fg = colors.bg,
    bg = colors.bg,
    sp = colors.fg,
  },
  ['@markup.heading.2.delimiter.vimdoc'] = {
    underline = true,
    nocombine = true,
    fg = colors.bg,
    bg = colors.bg,
    sp = colors.fg,
  },
  ['@markup.italic'] = { italic = true },
  ['@markup.link'] = { link = 'Identifier' },
  ['@markup.link.url'] = { link = 'Underlined' },
  ['@markup.raw'] = { link = 'Comment' },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.underline'] = { link = 'Underlined' },
  ['@module'] = { link = 'Identifier' },
  ['@module.builtin'] = { link = 'Special' },
  ['@number'] = { link = 'Number' },
  ['@number.float'] = { link = 'Float' },
  ['@operator'] = { link = 'Operator' },
  ['@property'] = { link = 'Identifier' },
  ['@punctuation'] = { link = 'Delimiter' },
  ['@punctuation.special'] = { link = 'Special' },
  ['@string'] = { link = 'String' },
  ['@string.escape'] = { link = 'SpecialChar' },
  ['@string.regexp'] = { link = '@string.special' },
  ['@string.special'] = { link = 'SpecialChar' },
  ['@string.special.url'] = { link = 'Underlined' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.builtin'] = { link = 'Special' },
  ['@type'] = { link = 'Type' },
  ['@type.builtin'] = { link = 'Special' },
  ['@type.definition'] = { link = 'Typedef' },
  ['@variable'] = { link = 'Identifier' },
  ['@variable.builtin'] = { link = 'Special' },
  ['@variable.member'] = { link = 'Identifier' },
  ['@variable.parameter'] = { link = 'Identifier' },
  ['@variable.parameter.builtin'] = { link = 'Special' },

  -- Git
  Added = { fg = colors.green_bright },
  Changed = { fg = colors.yellow_bright },
  Removed = { fg = colors.red_bright },
  GitSignsAdd = { link = 'Added' },
  GitSignsAddCul = { link = 'GitSignsAdd' },
  GitSignsAddLn = { link = 'DiffAdd' },
  GitSignsAddLnInline = { link = 'GitSignsAddInline' },
  GitSignsAddNr = { link = 'GitSignsAdd' },
  GitSignsAddInline = { link = 'TermCursor' },
  GitSignsAddPreview = { link = 'DiffAdd' },
  GitSignsChange = { link = 'Changed' },
  GitSignsChangeCul = { link = 'GitSignsChange' },
  GitSignsChangeLn = { link = 'DiffChange' },
  GitSignsChangeLnInline = { link = 'GitSignsChangeInline' },
  GitSignsChangeNr = { link = 'GitSignsChange' },
  GitSignsChangeInline = { link = 'TermCursor' },
  GitSignsChangedelete = { link = 'GitSignsChange' },
  GitSignsChangedeleteCul = { link = 'GitSignsChangeCul' },
  GitSignsChangedeleteLn = { link = 'GitSignsChangeLn' },
  GitSignsChangedeleteNr = { link = 'GitSignsChangeNr' },
  GitSignsCurrentLineBlame = { link = 'NonText' },
  GitSignsDelete = { link = 'Removed' },
  GitSignsDeleteCul = { link = 'GitSignsDelete' },
  GitSignsDeleteInline = { link = 'TermCursor' },
  GitSignsDeleteLn = {},
  GitSignsDeleteLnInline = { link = 'GitSignsDeleteInline' },
  GitSignsDeleteNr = { link = 'GitSignsDelete' },
  GitSignsDeletePreview = { link = 'DiffDelete' },
  GitSignsDeleteVirtLn = { link = 'DiffDelete' },
  GitSignsDeleteVirtLnInLine = { link = 'GitSignsDeleteLnInline' },
  GitSignsNoEOLPreview = { link = 'Constant' },
  GitSignsStagedAdd = { fg = colors.git_staged_add },
  GitSignsStagedAddCul = { fg = colors.git_staged_add },
  GitSignsStagedAddLn = { fg = '#7faf7f', bg = colors.git_staged_add },
  GitSignsStagedAddNr = { fg = colors.git_staged_add },
  GitSignsStagedChange = { fg = colors.git_staged_change },
  GitSignsStagedChangeCul = { fg = colors.git_staged_change },
  GitSignsStagedChangeLn = { fg = '#929292', bg = '#dadada' },
  GitSignsStagedChangeNr = { fg = colors.git_staged_change },
  GitSignsStagedChangedelete = { fg = colors.git_staged_change },
  GitSignsStagedChangedeleteCul = { fg = colors.git_staged_change },
  GitSignsStagedChangedeleteLn = { fg = '#929292', bg = '#dadada' },
  GitSignsStagedChangedeleteNr = { fg = colors.git_staged_change },
  GitSignsStagedDelete = { fg = colors.git_staged_delete },
  GitSignsStagedDeleteCul = { fg = colors.git_staged_delete },
  GitSignsStagedDeleteNr = { fg = colors.git_staged_delete },
  GitSignsStagedTopdelete = { fg = colors.git_staged_delete },
  GitSignsStagedTopdeleteCul = { fg = colors.git_staged_delete },
  GitSignsStagedTopdeleteLn = {},
  GitSignsStagedTopdeleteNr = { fg = colors.git_staged_delete },
  GitSignsStagedUntracked = { fg = colors.git_staged_add },
  GitSignsStagedUntrackedCul = { fg = colors.git_staged_add },
  GitSignsStagedUntrackedLn = { fg = '#7faf7f', bg = colors.git_staged_add },
  GitSignsStagedUntrackedNr = { fg = colors.git_staged_add },
  GitSignsTopdelete = { link = 'GitSignsDelete' },
  GitSignsTopdeleteCul = { link = 'GitSignsDeleteCul' },
  GitSignsTopdeleteLn = { link = 'GitSignsDeleteLn' },
  GitSignsTopdeleteNr = { link = 'GitSignsDeleteNr' },
  GitSignsUntracked = { link = 'GitSignsAdd' },
  GitSignsUntrackedCul = { link = 'GitSignsAddCul' },
  GitSignsUntrackedLn = { link = 'GitSignsAddLn' },
  GitSignsUntrackedNr = { link = 'GitSignsAddNr' },
  GitSignsVirtLnum = { link = 'GitSignsDeleteVirtLn' },

  -- BlinkCmp
  BlinkCmpDoc = { link = 'NormalFloat' },
  BlinkCmpDocBorder = { link = 'NormalFloat' },
  BlinkCmpDocCursorLine = { link = 'Visual' },
  BlinkCmpDocSeparator = { link = 'NormalFloat' },
  BlinkCmpGhostText = { link = 'NonText' },
  BlinkCmpKind = { link = 'PmenuKind' },
  BlinkCmpKindClass = { link = 'BlinkCmpKind' },
  BlinkCmpKindColor = { link = 'BlinkCmpKind' },
  BlinkCmpKindConstant = { link = 'BlinkCmpKind' },
  BlinkCmpKindConstructor = { link = 'BlinkCmpKind' },
  BlinkCmpKindEnum = { link = 'BlinkCmpKind' },
  BlinkCmpKindEnumMember = { link = 'BlinkCmpKind' },
  BlinkCmpKindEvent = { link = 'BlinkCmpKind' },
  BlinkCmpKindField = { link = 'BlinkCmpKind' },
  BlinkCmpKindFile = { link = 'BlinkCmpKind' },
  BlinkCmpKindFolder = { link = 'BlinkCmpKind' },
  BlinkCmpKindFunction = { link = 'BlinkCmpKind' },
  BlinkCmpKindInterface = { link = 'BlinkCmpKind' },
  BlinkCmpKindKeyword = { link = 'BlinkCmpKind' },
  BlinkCmpKindMethod = { link = 'BlinkCmpKind' },
  BlinkCmpKindModule = { link = 'BlinkCmpKind' },
  BlinkCmpKindOperator = { link = 'BlinkCmpKind' },
  BlinkCmpKindProperty = { link = 'BlinkCmpKind' },
  BlinkCmpKindReference = { link = 'BlinkCmpKind' },
  BlinkCmpKindSnippet = { link = 'BlinkCmpKind' },
  BlinkCmpKindStruct = { link = 'BlinkCmpKind' },
  BlinkCmpKindText = { link = 'BlinkCmpKind' },
  BlinkCmpKindTypeParameter = { link = 'BlinkCmpKind' },
  BlinkCmpKindUnit = { link = 'BlinkCmpKind' },
  BlinkCmpKindValue = { link = 'BlinkCmpKind' },
  BlinkCmpKindVariable = { link = 'BlinkCmpKind' },
  BlinkCmpLabelDeprecated = { link = 'PmenuExtra' },
  BlinkCmpLabelDescription = { link = 'PmenuExtra' },
  BlinkCmpLabelDetail = { link = 'PmenuExtra' },
  BlinkCmpMenu = { link = 'Pmenu' },
  BlinkCmpMenuBorder = { link = 'Pmenu' },
  BlinkCmpMenuSelection = { link = 'PmenuSel' },
  BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
  BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
  BlinkCmpSignatureHelp = { link = 'NormalFloat' },
  BlinkCmpSignatureHelpActiveParameter = { link = 'LspSignatureActiveParameter' },
  BlinkCmpSignatureHelpBorder = { link = 'NormalFloat' },
  BlinkCmpSource = { link = 'PmenuExtra' },

  -- Mini
  MiniStatuslineDevinfo = { link = 'StatusLine' },
  MiniStatuslineFileinfo = { link = 'StatusLine' },
  MiniStatuslineFilename = { link = 'StatusLineNC' },
  MiniStatuslineInactive = { link = 'StatusLineNC' },
  MiniStatuslineModeCommand = { link = 'DiffText' },
  MiniStatuslineModeInsert = { link = 'DiffChange' },
  MiniStatuslineModeNormal = { link = 'Cursor' },
  MiniStatuslineModeOther = { link = 'IncSearch' },
  MiniStatuslineModeReplace = { link = 'DiffDelete' },
  MiniStatuslineModeVisual = { link = 'DiffAdd' },
  MiniTablineCurrent = { link = 'TabLineSel' },
  MiniTablineFill = { link = 'Normal' },
  MiniTablineHidden = { link = 'TabLine' },
  MiniTablineModifiedCurrent = { link = 'StatusLine' },
  MiniTablineModifiedHidden = { link = 'StatusLineNC' },
  MiniTablineModifiedVisible = { link = 'StatusLine' },
  MiniTablineTabpagesection = { link = 'Search' },
  MiniTablineTrunc = { link = 'MiniTablineHidden' },
  MiniTablineVisible = { link = 'TabLineSel' },

  -- DAP
  DapUIBreakpointsCurrentLine = { link = 'CursorLineNr' },
  DapUIBreakpointsDisabledLine = { link = 'Comment' },
  DapUIBreakpointsInfo = { link = 'Statement' },
  DapUIBreakpointsLine = { link = 'DapUILineNumber' },
  DapUIBreakpointsPath = { link = 'Identifier' },
  DapUICurrentFrameName = { link = 'DapUIBreakpointsCurrentLine' },
  DapUIDecoration = { link = 'Identifier' },
  DapUIEndofBuffer = { link = 'EndOfBuffer' },
  DapUIFrameName = { link = 'Normal' },
  DapUIFloatBorder = { link = 'Identifier' },
  DapUIFloatNormal = { link = 'NormalFloat' },
  DapUILineNumber = { link = 'LineNr' },
  DapUIModifiedValue = { link = 'Function' },
  DapUINormal = { link = 'Normal' },
  DapUINormalNC = { link = 'Normal' },
  DapUIPlayPause = { link = 'Repeat' },
  DapUIPlayPauseNC = { link = 'Repeat' },
  DapUIRestart = { link = 'Repeat' },
  DapUIRestartNC = { link = 'Repeat' },
  DapUIScope = { link = 'Identifier' },
  DapUISource = { link = 'Define' },
  DapUIStepBack = { link = 'Label' },
  DapUIStepBackNC = { link = 'Label' },
  DapUIStepInto = { link = 'Label' },
  DapUIStepIntoNC = { link = 'Label' },
  DapUIStepOut = { link = 'Label' },
  DapUIStepOutNC = { link = 'Label' },
  DapUIStepOver = { link = 'Label' },
  DapUIStepOverNC = { link = 'Label' },
  DapUIStoppedThread = { link = 'Function' },
  DapUIStop = { link = 'PreProc' },
  DapUIStopNC = { link = 'PreProc' },
  DapUIThread = { link = 'Identifier' },
  DapUIType = { link = 'Type' },
  DapUIUnavailable = { link = 'Comment' },
  DapUIUnavailableNC = { link = 'Comment' },
  DapUIValue = { link = 'Normal' },
  DapUIVariable = { link = 'Normal' },
  DapUIWinSelect = { link = 'Special' },
  DapUIWatchesEmpty = { link = 'PreProc' },
  DapUIWatchesError = { link = 'PreProc' },
  DapUIWatchesValue = { link = 'Statement' },

  -- RenderMarkdown
  RenderMarkdownBullet = { link = 'Normal' },
  RenderMarkdownChecked = { link = '@markup.list.checked' },
  RenderMarkdownCode = { link = 'ColorColumn' },
  RenderMarkdownCodeBorder = { link = 'RenderMarkdownCode' },
  RenderMarkdownCodeFallback = { link = 'Normal' },
  RenderMarkdownCodeInfo = { link = '@label' },
  RenderMarkdownCodeInline = { link = 'RenderMarkdownCode' },
  RenderMarkdownDash = { link = 'LineNr' },
  RenderMarkdownError = { link = 'DiagnosticError' },
  RenderMarkdownH1 = { link = '@markup.heading.1.markdown' },
  RenderMarkdownH1Bg = { link = 'DiffText' },
  RenderMarkdownH2 = { link = '@markup.heading.2.markdown' },
  RenderMarkdownH2Bg = { link = 'DiffAdd' },
  RenderMarkdownH3 = { link = '@markup.heading.3.markdown' },
  RenderMarkdownH3Bg = { link = 'DiffChange' },
  RenderMarkdownH4 = { link = '@markup.heading.4.markdown' },
  RenderMarkdownH4Bg = { link = 'DiffDelete' },
  RenderMarkdownH5 = { link = '@markup.heading.5.markdown' },
  RenderMarkdownH5Bg = { link = 'Visual' },
  RenderMarkdownH6 = { link = '@markup.heading.6.markdown' },
  RenderMarkdownH6Bg = { link = 'CursorColumn' },
  RenderMarkdownHint = { link = 'DiagnosticHint' },
  RenderMarkdownHtmlComment = { link = '@comment' },
  RenderMarkdownIndent = { link = 'Whitespace' },
  RenderMarkdownInfo = { link = 'DiagnosticInfo' },
  RenderMarkdownInlineHighlight = { link = 'RenderMarkdownCodeInline' },
  RenderMarkdownLink = { link = '@markup.link.label.markdown_inline' },
  RenderMarkdownLinkTitle = { link = '@markup.link.markdown_inline' },
  RenderMarkdownMath = { link = '@markup.math' },
  RenderMarkdownQuote = { link = '@markup.quote' },
  RenderMarkdownQuote1 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownQuote2 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownQuote3 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownQuote4 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownQuote5 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownQuote6 = { link = 'RenderMarkdownQuote' },
  RenderMarkdownSign = { link = 'SignColumn' },
  RenderMarkdownSuccess = { link = 'DiagnosticOk' },
  RenderMarkdownTableFill = { link = 'Conceal' },
  RenderMarkdownTableHead = { link = '@markup.heading' },
  RenderMarkdownTableRow = { link = 'Normal' },
  RenderMarkdownTodo = { link = '@markup.raw' },
  RenderMarkdownUnchecked = { link = '@markup.list.unchecked' },
  RenderMarkdownWarn = { link = 'DiagnosticWarn' },
  RenderMarkdownWikiLink = { link = 'RenderMarkdownLink' },

  -- Aerial
  AerialArray = { link = 'AerialNormal' },
  AerialArrayIcon = { link = 'Identifier' },
  AerialBoolean = { link = 'AerialNormal' },
  AerialBooleanIcon = { link = 'Identifier' },
  AerialClass = { link = 'AerialNormal' },
  AerialClassIcon = { link = 'Type' },
  AerialConstant = { link = 'AerialNormal' },
  AerialConstantIcon = { link = 'Constant' },
  AerialConstructor = { link = 'AerialNormal' },
  AerialConstructorIcon = { link = 'Special' },
  AerialEnum = { link = 'AerialNormal' },
  AerialEnumIcon = { link = 'Type' },
  AerialEnumMember = { link = 'AerialNormal' },
  AerialEnumMemberIcon = { link = 'Identifier' },
  AerialEvent = { link = 'AerialNormal' },
  AerialEventIcon = { link = 'Identifier' },
  AerialField = { link = 'AerialNormal' },
  AerialFieldIcon = { link = 'Identifier' },
  AerialFile = { link = 'AerialNormal' },
  AerialFileIcon = { link = 'Identifier' },
  AerialFunction = { link = 'AerialNormal' },
  AerialFunctionIcon = { link = 'Function' },
  AerialGuide = {},
  AerialGuide1 = { link = 'AerialGuide' },
  AerialGuide2 = { link = 'AerialGuide' },
  AerialGuide3 = { link = 'AerialGuide' },
  AerialGuide4 = { link = 'AerialGuide' },
  AerialGuide5 = { link = 'AerialGuide' },
  AerialGuide6 = { link = 'AerialGuide' },
  AerialGuide7 = { link = 'AerialGuide' },
  AerialGuide8 = { link = 'AerialGuide' },
  AerialGuide9 = { link = 'AerialGuide' },
  AerialInterface = { link = 'AerialNormal' },
  AerialInterfaceIcon = { link = 'Type' },
  AerialKey = { link = 'AerialNormal' },
  AerialKeyIcon = { link = 'Identifier' },
  AerialLine = { link = 'QuickFixLine' },
  AerialLineNC = { link = 'AerialLine' },
  AerialMethod = { link = 'AerialNormal' },
  AerialMethodIcon = { link = 'Function' },
  AerialModule = { link = 'AerialNormal' },
  AerialModuleIcon = { link = 'Include' },
  AerialNamespace = { link = 'AerialNormal' },
  AerialNamespaceIcon = { link = 'Include' },
  AerialNormal = {},
  AerialNormalFloat = {},
  AerialNull = { link = 'AerialNormal' },
  AerialNullIcon = { link = 'Identifier' },
  AerialNumber = { link = 'AerialNormal' },
  AerialNumberIcon = { link = 'Identifier' },
  AerialObject = { link = 'AerialNormal' },
  AerialObjectIcon = { link = 'Identifier' },
  AerialOperator = { link = 'AerialNormal' },
  AerialOperatorIcon = { link = 'Identifier' },
  AerialPackage = { link = 'AerialNormal' },
  AerialPackageIcon = { link = 'Include' },
  AerialPrivate = { link = 'Comment' },
  AerialProperty = { link = 'AerialNormal' },
  AerialPropertyIcon = { link = 'Identifier' },
  AerialProtected = { link = 'Comment' },
  AerialString = { link = 'AerialNormal' },
  AerialStringIcon = { link = 'Identifier' },
  AerialStruct = { link = 'AerialNormal' },
  AerialStructIcon = { link = 'Type' },
  AerialTypeParameter = { link = 'AerialNormal' },
  AerialTypeParameterIcon = { link = 'Identifier' },
  AerialVariable = { link = 'AerialNormal' },
  AerialVariableIcon = { link = 'Identifier' },

  -- Fyler
  FylerBorder = { link = 'FylerNormal' },
  FylerFSDirectoryIcon = { fg = colors.blue },
  FylerFSDirectoryName = {},
  FylerFSFile = { fg = colors.fg_white },
  FylerFSLink = { fg = colors.fg_comment },
  FylerGitAdded = { fg = colors.green },
  FylerGitConflict = { fg = colors.fg_white },
  FylerGitDeleted = { fg = colors.fg_white },
  FylerGitIgnored = { fg = colors.fg_comment },
  FylerGitModified = { fg = colors.orange },
  FylerGitRenamed = { fg = colors.orange },
  FylerGitStaged = { fg = colors.green },
  FylerGitUnstaged = { fg = colors.purple },
  FylerGitUntracked = { fg = colors.blue },
  FylerGrey = { fg = colors.fg_comment },
  FylerGreen = { fg = colors.green },
  FylerIndentMarker = { link = 'FylerGrey' },
  FylerNormal = { link = 'Normal' },
  FylerNormalNC = { link = 'NormalNC' },
  FylerRed = { fg = colors.fg_white },
  FylerYellow = { fg = colors.orange },

  -- Todo comments
  TodoBgFIX = { bold = true, fg = colors.fg, bg = '#ff0000' },
  TodoBgHACK = { bold = true, fg = colors.fg, bg = colors.orange },
  TodoBgNOTE = { bold = true, fg = colors.fg, bg = colors.cyan_bright },
  TodoBgPERF = { bold = true, fg = colors.bg, bg = colors.magenta },
  TodoBgTEST = { bold = true, fg = colors.bg, bg = colors.magenta },
  TodoBgTODO = { bold = true, fg = colors.bg, bg = colors.blue_bright },
  TodoBgWARN = { bold = true, fg = colors.fg, bg = colors.orange },
  TodoFgFIX = { fg = '#ff0000' },
  TodoFgHACK = { fg = colors.orange },
  TodoFgNOTE = { fg = colors.cyan_bright },
  TodoFgPERF = { fg = colors.magenta },
  TodoFgTEST = { fg = colors.magenta },
  TodoFgTODO = { fg = colors.blue_bright },
  TodoFgWARN = { fg = colors.orange },
  TodoSignFIX = { fg = '#ff0000' },
  TodoSignHACK = { fg = colors.orange },
  TodoSignNOTE = { fg = colors.cyan_bright },
  TodoSignPERF = { fg = colors.magenta },
  TodoSignTEST = { fg = colors.magenta },
  TodoSignTODO = { fg = colors.blue_bright },
  TodoSignWARN = { fg = colors.orange },

  -- Terminal and messages
  Terminal = { link = 'Normal' },
  MessageWindow = { link = 'Pmenu' },
  PopupNotification = { link = 'Todo' },
  PopupSelected = { link = 'PmenuSel' },

  -- Debug
  debugBreakpoint = { fg = colors.cyan, reverse = true },
  debugPC = { fg = colors.blue, reverse = true },

  -- Nvim internal
  NvimInternalError = { fg = '#ff0000', bg = '#ff0000' },
  NvimAssignment = { link = 'Operator' },
  NvimPlainAssignment = { link = 'NvimAssignment' },
  NvimAugmentedAssignment = { link = 'NvimAssignment' },
  NvimAssignmentWithAddition = { link = 'NvimAugmentedAssignment' },
  NvimAssignmentWithSubtraction = { link = 'NvimAugmentedAssignment' },
  NvimAssignmentWithConcatenation = { link = 'NvimAugmentedAssignment' },
  NvimOperator = { link = 'Operator' },
  NvimUnaryOperator = { link = 'NvimOperator' },
  NvimUnaryPlus = { link = 'NvimUnaryOperator' },
  NvimUnaryMinus = { link = 'NvimUnaryOperator' },
  NvimNot = { link = 'NvimUnaryOperator' },
  NvimBinaryOperator = { link = 'NvimOperator' },
  NvimComparison = { link = 'NvimBinaryOperator' },
  NvimComparisonModifier = { link = 'NvimComparison' },
  NvimBinaryPlus = { link = 'NvimBinaryOperator' },
  NvimBinaryMinus = { link = 'NvimBinaryOperator' },
  NvimConcat = { link = 'NvimBinaryOperator' },
  NvimConcatOrSubscript = { link = 'NvimConcat' },
  NvimOr = { link = 'NvimBinaryOperator' },
  NvimAnd = { link = 'NvimBinaryOperator' },
  NvimMultiplication = { link = 'NvimBinaryOperator' },
  NvimDivision = { link = 'NvimBinaryOperator' },
  NvimMod = { link = 'NvimBinaryOperator' },
  NvimTernary = { link = 'NvimOperator' },
  NvimTernaryColon = { link = 'NvimTernary' },
  NvimParenthesis = { link = 'Delimiter' },
  NvimLambda = { link = 'NvimParenthesis' },
  NvimNestingParenthesis = { link = 'NvimParenthesis' },
  NvimCallingParenthesis = { link = 'NvimParenthesis' },
  NvimSubscript = { link = 'NvimParenthesis' },
  NvimSubscriptBracket = { link = 'NvimSubscript' },
  NvimSubscriptColon = { link = 'NvimSubscript' },
  NvimCurly = { link = 'NvimSubscript' },
  NvimContainer = { link = 'NvimParenthesis' },
  NvimDict = { link = 'NvimContainer' },
  NvimList = { link = 'NvimContainer' },
  NvimIdentifier = { link = 'Identifier' },
  NvimIdentifierScope = { link = 'NvimIdentifier' },
  NvimIdentifierScopeDelimiter = { link = 'NvimIdentifier' },
  NvimIdentifierName = { link = 'NvimIdentifier' },
  NvimIdentifierKey = { link = 'NvimIdentifier' },
  NvimColon = { link = 'Delimiter' },
  NvimComma = { link = 'Delimiter' },
  NvimArrow = { link = 'Delimiter' },
  NvimRegister = { link = 'SpecialChar' },
  NvimNumber = { link = 'Number' },
  NvimFloat = { link = 'NvimNumber' },
  NvimNumberPrefix = { link = 'Type' },
  NvimOptionSigil = { link = 'Type' },
  NvimOptionName = { link = 'NvimIdentifier' },
  NvimOptionScope = { link = 'NvimIdentifierScope' },
  NvimOptionScopeDelimiter = { link = 'NvimIdentifierScopeDelimiter' },
  NvimEnvironmentSigil = { link = 'NvimOptionSigil' },
  NvimEnvironmentName = { link = 'NvimIdentifier' },
  NvimString = { link = 'String' },
  NvimStringBody = { link = 'NvimString' },
  NvimStringQuote = { link = 'NvimString' },
  NvimStringSpecial = { link = 'SpecialChar' },
  NvimSingleQuote = { link = 'NvimStringQuote' },
  NvimSingleQuotedBody = { link = 'NvimStringBody' },
  NvimSingleQuotedQuote = { link = 'NvimStringSpecial' },
  NvimDoubleQuote = { link = 'NvimStringQuote' },
  NvimDoubleQuotedBody = { link = 'NvimStringBody' },
  NvimDoubleQuotedEscape = { link = 'NvimStringSpecial' },
  NvimFigureBrace = { link = 'NvimInternalError' },
  NvimSingleQuotedUnknownEscape = { link = 'NvimInternalError' },
  NvimSpacing = { link = 'Normal' },
  NvimInvalidSingleQuotedUnknownEscape = { link = 'NvimInternalError' },
  NvimInvalid = { link = 'Error' },
  NvimInvalidAssignment = { link = 'NvimInvalid' },
  NvimInvalidPlainAssignment = { link = 'NvimInvalidAssignment' },
  NvimInvalidAugmentedAssignment = { link = 'NvimInvalidAssignment' },
  NvimInvalidAssignmentWithAddition = { link = 'NvimInvalidAugmentedAssignment' },
  NvimInvalidAssignmentWithSubtraction = { link = 'NvimInvalidAugmentedAssignment' },
  NvimInvalidAssignmentWithConcatenation = { link = 'NvimInvalidAugmentedAssignment' },
  NvimInvalidOperator = { link = 'NvimInvalid' },
  NvimInvalidUnaryOperator = { link = 'NvimInvalidOperator' },
  NvimInvalidUnaryPlus = { link = 'NvimInvalidUnaryOperator' },
  NvimInvalidUnaryMinus = { link = 'NvimInvalidUnaryOperator' },
  NvimInvalidNot = { link = 'NvimInvalidUnaryOperator' },
  NvimInvalidBinaryOperator = { link = 'NvimInvalidOperator' },
  NvimInvalidComparison = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidComparisonModifier = { link = 'NvimInvalidComparison' },
  NvimInvalidBinaryPlus = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidBinaryMinus = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidConcat = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidConcatOrSubscript = { link = 'NvimInvalidConcat' },
  NvimInvalidOr = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidAnd = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidMultiplication = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidDivision = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidMod = { link = 'NvimInvalidBinaryOperator' },
  NvimInvalidTernary = { link = 'NvimInvalidOperator' },
  NvimInvalidTernaryColon = { link = 'NvimInvalidTernary' },
  NvimInvalidDelimiter = { link = 'NvimInvalid' },
  NvimInvalidParenthesis = { link = 'NvimInvalidDelimiter' },
  NvimInvalidLambda = { link = 'NvimInvalidParenthesis' },
  NvimInvalidNestingParenthesis = { link = 'NvimInvalidParenthesis' },
  NvimInvalidCallingParenthesis = { link = 'NvimInvalidParenthesis' },
  NvimInvalidSubscript = { link = 'NvimInvalidParenthesis' },
  NvimInvalidSubscriptBracket = { link = 'NvimInvalidSubscript' },
  NvimInvalidSubscriptColon = { link = 'NvimInvalidSubscript' },
  NvimInvalidCurly = { link = 'NvimInvalidSubscript' },
  NvimInvalidContainer = { link = 'NvimInvalidParenthesis' },
  NvimInvalidDict = { link = 'NvimInvalidContainer' },
  NvimInvalidList = { link = 'NvimInvalidContainer' },
  NvimInvalidValue = { link = 'NvimInvalid' },
  NvimInvalidIdentifier = { link = 'NvimInvalidValue' },
  NvimInvalidIdentifierScope = { link = 'NvimInvalidIdentifier' },
  NvimInvalidIdentifierScopeDelimiter = { link = 'NvimInvalidIdentifier' },
  NvimInvalidIdentifierName = { link = 'NvimInvalidIdentifier' },
  NvimInvalidIdentifierKey = { link = 'NvimInvalidIdentifier' },
  NvimInvalidColon = { link = 'NvimInvalidDelimiter' },
  NvimInvalidComma = { link = 'NvimInvalidDelimiter' },
  NvimInvalidArrow = { link = 'NvimInvalidDelimiter' },
  NvimInvalidRegister = { link = 'NvimInvalidValue' },
  NvimInvalidNumber = { link = 'NvimInvalidValue' },
  NvimInvalidFloat = { link = 'NvimInvalidNumber' },
  NvimInvalidNumberPrefix = { link = 'NvimInvalidNumber' },
  NvimInvalidOptionSigil = { link = 'NvimInvalidIdentifier' },
  NvimInvalidOptionName = { link = 'NvimInvalidIdentifier' },
  NvimInvalidOptionScope = { link = 'NvimInvalidIdentifierScope' },
  NvimInvalidOptionScopeDelimiter = { link = 'NvimInvalidIdentifierScopeDelimiter' },
  NvimInvalidEnvironmentSigil = { link = 'NvimInvalidOptionSigil' },
  NvimInvalidEnvironmentName = { link = 'NvimInvalidIdentifier' },
  NvimInvalidString = { link = 'NvimInvalidValue' },
  NvimInvalidStringBody = { link = 'NvimStringBody' },
  NvimInvalidStringQuote = { link = 'NvimInvalidString' },
  NvimInvalidStringSpecial = { link = 'NvimStringSpecial' },
  NvimInvalidSingleQuote = { link = 'NvimInvalidStringQuote' },
  NvimInvalidSingleQuotedBody = { link = 'NvimInvalidStringBody' },
  NvimInvalidSingleQuotedQuote = { link = 'NvimInvalidStringSpecial' },
  NvimInvalidDoubleQuote = { link = 'NvimInvalidStringQuote' },
  NvimInvalidDoubleQuotedBody = { link = 'NvimInvalidStringBody' },
  NvimInvalidDoubleQuotedEscape = { link = 'NvimInvalidStringSpecial' },
  NvimInvalidDoubleQuotedUnknownEscape = { link = 'NvimInvalidValue' },
  NvimInvalidFigureBrace = { link = 'NvimInvalidDelimiter' },
  NvimInvalidSpacing = { link = 'ErrorMsg' },
  NvimDoubleQuotedUnknownEscape = { link = 'NvimInvalidValue' },

  -- Snippet
  SnippetTabstop = { link = 'Visual' },
  ComplMatchIns = {},
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
